apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "okofw-example.openstack.org/v1beta1",
          "kind": "RWExternal",
          "metadata": {
            "name": "rwexternal-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "okofw-example.openstack.org/v1beta1",
          "kind": "ServiceWithDB",
          "metadata": {
            "name": "servicewithdb-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "okofw-example.openstack.org/v1beta1",
          "kind": "Simple",
          "metadata": {
            "name": "simple-sample"
          },
          "spec": {
            "divident": 10,
            "divisor": 5
          }
        }
      ]
    capabilities: Basic Install
    operatorframework.io/suggested-namespace: openstack
    operators.operatorframework.io/builder: operator-sdk-v1.23.0
    operators.operatorframework.io/operator-type: non-standalone
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: okofw.v0.0.3
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: RWExternal is the Schema for the rwexternals API
      displayName: RWExternal
      kind: RWExternal
      name: rwexternals.okofw-example.openstack.org
      version: v1beta1
    - description: ServiceWithDB is the Schema for the servicewithdbs API
      displayName: Service With DB
      kind: ServiceWithDB
      name: servicewithdbs.okofw-example.openstack.org
      version: v1beta1
    - description: Simple is the Schema for the simples API
      displayName: Simple
      kind: Simple
      name: simples.okofw-example.openstack.org
      version: v1beta1
  description: OKOFW Operator
  displayName: OKOFW Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - okofw-example.openstack.org
          resources:
          - rwexternals
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - okofw-example.openstack.org
          resources:
          - rwexternals/finalizers
          verbs:
          - update
        - apiGroups:
          - okofw-example.openstack.org
          resources:
          - rwexternals/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - okofw-example.openstack.org
          resources:
          - servicewithdbs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - okofw-example.openstack.org
          resources:
          - servicewithdbs/finalizers
          verbs:
          - update
        - apiGroups:
          - okofw-example.openstack.org
          resources:
          - servicewithdbs/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - okofw-example.openstack.org
          resources:
          - simples
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - okofw-example.openstack.org
          resources:
          - simples/finalizers
          verbs:
          - update
        - apiGroups:
          - okofw-example.openstack.org
          resources:
          - simples/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: okofw-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: okofw-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/gibi/okofw-operator:v0.0.3
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: okofw-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: okofw-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - OpenStack
  links:
  - name: OKOFW Operator
    url: https://github.com/gibizer/okofw
  maturity: beta
  provider:
    name: Red Hat Inc.
    url: https://redhat.com/
  version: 0.0.3
