# permissions for end users to view rwexternals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rwexternal-viewer-role
rules:
- apiGroups:
  - okofw-example.openstack.org
  resources:
  - rwexternals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - okofw-example.openstack.org
  resources:
  - rwexternals/status
  verbs:
  - get
